package pacote;

import java.awt.event.KeyEvent;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;

public class FrmChat extends javax.swing.JFrame {
    
    public String msg = "";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmChat.class.getName());

    /**
     * Creates new form frmChat
     */
    public FrmChat() {
        initComponents();
        Thread.startVirtualThread(() -> {
            while(true){
                try{
                    Socket client = new Socket("200.128.141.103", 6661);
                    ObjectInputStream input = new ObjectInputStream(client.getInputStream());
                    String msgs = input.readUTF();
                    input.close();
                    client.close();
                    edtConversa.setText("");
                    HTMLEditorKit kit = (HTMLEditorKit) edtConversa.getEditorKit();
                    HTMLDocument doc = (HTMLDocument) edtConversa.getDocument();
                    kit.insertHTML(doc, doc.getLength(), msgs, 0, 0, null);
                } catch(Exception error){
                    System.out.println("FrmChat::FrmChat: Error " + error.getMessage());
                    JOptionPane.showMessageDialog(null, "FrmChat::FrmChat: Error " + error.getMessage());
                }
            }
        });
    }

    public void gerarAndEnviarMsg(){
        this.msg = "";
        this.msg += "<img src='/pacote/images/" + Util.avatar + "' width='24px' height='24px'> ";
        this.msg += "<font color='" + Util.cor + "'><b>" + Util.nickname + " </b></font>";
        
        if(selectModo.getSelectedItem().toString().equals("Fala")){
            this.msg += "fala: " + this.inputTxtMensagem.getText();
        } else if(selectModo.getSelectedItem().toString().equals("Grita")){
            this.msg += "<b>grita: </b> <font size='+2'>" + this.inputTxtMensagem.getText().toUpperCase() + "</font>";
        } else if(selectModo.getSelectedItem().toString().equals("Sussurra")){
            this.msg += "<font size='-1'><i>sussura: </i>" + this.inputTxtMensagem.getText().toLowerCase() + "</font>";
        } else if(selectModo.getSelectedItem().toString().equals("Xinga")){
            this.msg += "<font size='+1' color='red'><b><u>xinga: " + this.inputTxtMensagem.getText().toUpperCase() + "</u></b></font>";
        }
        
        if(!selectEmoji.getSelectedItem().toString().equals("Nenhum")){
            this.msg += "<img src='images/" + selectEmoji.getSelectedItem().toString() + ".png' width='15' height='15'>";
        }
        
        this.msg += "<br>";
        
        ArrayList<String> codigos = new ArrayList<>();        
        ArrayList<String> simbolos = new ArrayList<>();
        
        codigos.add(":-)");
        simbolos.add("&#128512;");
        codigos.add(";-)");
        simbolos.add("&#128521;");
        codigos.add("x-x");
        simbolos.add("&#128565;");
        codigos.add(":-(");
        simbolos.add("&#128551;");
        codigos.add(";-;");
        simbolos.add("&#128557;");
        
        for(int i=0; i < codigos.size(); i++){
            this.msg = this.msg.replace(codigos.get(i), simbolos.get(i));
        }
        
        inputTxtMensagem.setText("");
        selectModo.setSelectedIndex(0);
        selectEmoji.setSelectedIndex(0);
        
        try{
            Socket client = new Socket("200.128.141.103", 6662);
            ObjectOutputStream output = new ObjectOutputStream(client.getOutputStream());
            output.writeUTF(this.msg);
            output.close();
            client.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "FrmChat::gerarAndEnviarMsg(): Erro " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrConversa = new javax.swing.JScrollPane();
        edtConversa = new javax.swing.JEditorPane();
        lblMensagem = new javax.swing.JLabel();
        inputTxtMensagem = new javax.swing.JTextField();
        lblModo = new javax.swing.JLabel();
        selectModo = new javax.swing.JComboBox<>();
        lblEmoji = new javax.swing.JLabel();
        selectEmoji = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat");
        setName("fmrChat"); // NOI18N

        scrConversa.setName("scrConversa"); // NOI18N

        edtConversa.setContentType("text/html"); // NOI18N
        scrConversa.setViewportView(edtConversa);

        lblMensagem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMensagem.setText("Mensagem:");
        lblMensagem.setName("lblMensagem"); // NOI18N

        inputTxtMensagem.setName("inputTxtMensagem"); // NOI18N
        inputTxtMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTxtMensagemKeyPressed(evt);
            }
        });

        lblModo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblModo.setText("Modo:");
        lblModo.setName("lblModo"); // NOI18N

        selectModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fala", "Grita", "Sussurra", "Xinga" }));
        selectModo.setName("selectModo"); // NOI18N

        lblEmoji.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmoji.setText("Emoji:");
        lblEmoji.setName("lblEmoji"); // NOI18N

        selectEmoji.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Coracao", "Dinheiro", "Beijo", " " }));
        selectEmoji.setName("selectEmoji"); // NOI18N

        btnEnviar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setName("btnEnviar"); // NOI18N
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrConversa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTxtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblModo)
                        .addGap(12, 12, 12)
                        .addComponent(selectModo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmoji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectEmoji, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrConversa, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(inputTxtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModo)
                    .addComponent(selectModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmoji)
                    .addComponent(selectEmoji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        this.gerarAndEnviarMsg();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void inputTxtMensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTxtMensagemKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.gerarAndEnviarMsg();
        }
    }//GEN-LAST:event_inputTxtMensagemKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmChat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JEditorPane edtConversa;
    private javax.swing.JTextField inputTxtMensagem;
    private javax.swing.JLabel lblEmoji;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblModo;
    private javax.swing.JScrollPane scrConversa;
    private javax.swing.JComboBox<String> selectEmoji;
    private javax.swing.JComboBox<String> selectModo;
    // End of variables declaration//GEN-END:variables
}
